// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snowflakeMessages.proto

package snowflakes.cuda.kask.eti.pg.gda.pl.commons;

public final class SnowflakeMessages {
  private SnowflakeMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SnowflakeDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:commons.SnowflakeData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    java.util.List<SnowflakeData.MyMapField>
        getMapFieldList();
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    SnowflakeData.MyMapField getMapField(int index);
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    int getMapFieldCount();
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    java.util.List<? extends SnowflakeData.MyMapFieldOrBuilder>
        getMapFieldOrBuilderList();
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    SnowflakeData.MyMapFieldOrBuilder getMapFieldOrBuilder(
            int index);

    /**
     * <code>optional int32 totalMessageSize = 2;</code>
     */
    boolean hasTotalMessageSize();
    /**
     * <code>optional int32 totalMessageSize = 2;</code>
     */
    int getTotalMessageSize();

    /**
     * <code>optional int32 slaveCapacity = 3;</code>
     */
    boolean hasSlaveCapacity();
    /**
     * <code>optional int32 slaveCapacity = 3;</code>
     */
    int getSlaveCapacity();

    /**
     * <code>optional int32 slaveId = 4;</code>
     */
    boolean hasSlaveId();
    /**
     * <code>optional int32 slaveId = 4;</code>
     */
    int getSlaveId();

    /**
     * <code>optional bool endOfWork = 5;</code>
     */
    boolean hasEndOfWork();
    /**
     * <code>optional bool endOfWork = 5;</code>
     */
    boolean getEndOfWork();

    /**
     * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
     */
    boolean hasSnowflakeTask();
    /**
     * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
     */
    SnowflakeData.SnowflakeTask getSnowflakeTask();
    /**
     * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
     */
    SnowflakeData.SnowflakeTaskOrBuilder getSnowflakeTaskOrBuilder();
  }
  /**
   * Protobuf type {@code commons.SnowflakeData}
   */
  public static final class SnowflakeData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:commons.SnowflakeData)
      SnowflakeDataOrBuilder {
    // Use SnowflakeData.newBuilder() to construct.
    private SnowflakeData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SnowflakeData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SnowflakeData defaultInstance;
    public static SnowflakeData getDefaultInstance() {
      return defaultInstance;
    }

    public SnowflakeData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SnowflakeData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                mapField_ = new java.util.ArrayList<MyMapField>();
                mutable_bitField0_ |= 0x00000001;
              }
              mapField_.add(input.readMessage(MyMapField.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              totalMessageSize_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              slaveCapacity_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              slaveId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              endOfWork_ = input.readBool();
              break;
            }
            case 50: {
              SnowflakeTask.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = snowflakeTask_.toBuilder();
              }
              snowflakeTask_ = input.readMessage(SnowflakeTask.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(snowflakeTask_);
                snowflakeTask_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          mapField_ = java.util.Collections.unmodifiableList(mapField_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SnowflakeMessages.internal_static_commons_SnowflakeData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SnowflakeMessages.internal_static_commons_SnowflakeData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SnowflakeData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<SnowflakeData> PARSER =
        new com.google.protobuf.AbstractParser<SnowflakeData>() {
      public SnowflakeData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnowflakeData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<SnowflakeData> getParserForType() {
      return PARSER;
    }

    public interface MyMapFieldOrBuilder extends
        // @@protoc_insertion_point(interface_extends:commons.SnowflakeData.MyMapField)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>optional int32 key = 1;</code>
       */
      int getKey();

      /**
       * <code>repeated float value = 2;</code>
       */
      java.util.List<Float> getValueList();
      /**
       * <code>repeated float value = 2;</code>
       */
      int getValueCount();
      /**
       * <code>repeated float value = 2;</code>
       */
      float getValue(int index);
    }
    /**
     * Protobuf type {@code commons.SnowflakeData.MyMapField}
     */
    public static final class MyMapField extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:commons.SnowflakeData.MyMapField)
        MyMapFieldOrBuilder {
      // Use MyMapField.newBuilder() to construct.
      private MyMapField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MyMapField(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MyMapField defaultInstance;
      public static MyMapField getDefaultInstance() {
        return defaultInstance;
      }

      public MyMapField getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MyMapField(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                key_ = input.readInt32();
                break;
              }
              case 21: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  value_ = new java.util.ArrayList<Float>();
                  mutable_bitField0_ |= 0x00000002;
                }
                value_.add(input.readFloat());
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                  value_ = new java.util.ArrayList<Float>();
                  mutable_bitField0_ |= 0x00000002;
                }
                while (input.getBytesUntilLimit() > 0) {
                  value_.add(input.readFloat());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            value_ = java.util.Collections.unmodifiableList(value_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_MyMapField_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_MyMapField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMapField.class, Builder.class);
      }

      public static com.google.protobuf.Parser<MyMapField> PARSER =
          new com.google.protobuf.AbstractParser<MyMapField>() {
        public MyMapField parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MyMapField(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<MyMapField> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private int key_;
      /**
       * <code>optional int32 key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 key = 1;</code>
       */
      public int getKey() {
        return key_;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private java.util.List<Float> value_;
      /**
       * <code>repeated float value = 2;</code>
       */
      public java.util.List<Float>
          getValueList() {
        return value_;
      }
      /**
       * <code>repeated float value = 2;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated float value = 2;</code>
       */
      public float getValue(int index) {
        return value_.get(index);
      }

      private void initFields() {
        key_ = 0;
        value_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, key_);
        }
        for (int i = 0; i < value_.size(); i++) {
          output.writeFloat(2, value_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, key_);
        }
        {
          int dataSize = 0;
          dataSize = 4 * getValueList().size();
          size += dataSize;
          size += 1 * getValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static MyMapField parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MyMapField parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MyMapField parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MyMapField parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MyMapField parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static MyMapField parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static MyMapField parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static MyMapField parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static MyMapField parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static MyMapField parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(MyMapField prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code commons.SnowflakeData.MyMapField}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:commons.SnowflakeData.MyMapField)
          MyMapFieldOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SnowflakeMessages.internal_static_commons_SnowflakeData_MyMapField_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SnowflakeMessages.internal_static_commons_SnowflakeData_MyMapField_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MyMapField.class, Builder.class);
        }

        // Construct using snowflakes.cuda.kask.eti.pg.gda.pl.commons.SnowflakeMessages.SnowflakeData.MyMapField.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SnowflakeMessages.internal_static_commons_SnowflakeData_MyMapField_descriptor;
        }

        public MyMapField getDefaultInstanceForType() {
          return MyMapField.getDefaultInstance();
        }

        public MyMapField build() {
          MyMapField result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public MyMapField buildPartial() {
          MyMapField result = new MyMapField(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            value_ = java.util.Collections.unmodifiableList(value_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MyMapField) {
            return mergeFrom((MyMapField)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MyMapField other) {
          if (other == MyMapField.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MyMapField parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MyMapField) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int key_ ;
        /**
         * <code>optional int32 key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 key = 1;</code>
         */
        public int getKey() {
          return key_;
        }
        /**
         * <code>optional int32 key = 1;</code>
         */
        public Builder setKey(int value) {
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = 0;
          onChanged();
          return this;
        }

        private java.util.List<Float> value_ = java.util.Collections.emptyList();
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            value_ = new java.util.ArrayList<Float>(value_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public java.util.List<Float>
            getValueList() {
          return java.util.Collections.unmodifiableList(value_);
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public int getValueCount() {
          return value_.size();
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public float getValue(int index) {
          return value_.get(index);
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public Builder setValue(
            int index, float value) {
          ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public Builder addValue(float value) {
          ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public Builder addAllValue(
            Iterable<? extends Float> values) {
          ensureValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, value_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated float value = 2;</code>
         */
        public Builder clearValue() {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:commons.SnowflakeData.MyMapField)
      }

      static {
        defaultInstance = new MyMapField(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:commons.SnowflakeData.MyMapField)
    }

    public interface SnowflakeTaskOrBuilder extends
        // @@protoc_insertion_point(interface_extends:commons.SnowflakeData.SnowflakeTask)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 currentSnowflakesCount = 1;</code>
       */
      boolean hasCurrentSnowflakesCount();
      /**
       * <code>optional int32 currentSnowflakesCount = 1;</code>
       */
      int getCurrentSnowflakesCount();

      /**
       * <code>optional float windForce = 2;</code>
       */
      boolean hasWindForce();
      /**
       * <code>optional float windForce = 2;</code>
       */
      float getWindForce();

      /**
       * <code>optional float windAngle = 3;</code>
       */
      boolean hasWindAngle();
      /**
       * <code>optional float windAngle = 3;</code>
       */
      float getWindAngle();
    }
    /**
     * Protobuf type {@code commons.SnowflakeData.SnowflakeTask}
     */
    public static final class SnowflakeTask extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:commons.SnowflakeData.SnowflakeTask)
        SnowflakeTaskOrBuilder {
      // Use SnowflakeTask.newBuilder() to construct.
      private SnowflakeTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SnowflakeTask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SnowflakeTask defaultInstance;
      public static SnowflakeTask getDefaultInstance() {
        return defaultInstance;
      }

      public SnowflakeTask getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SnowflakeTask(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                currentSnowflakesCount_ = input.readInt32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                windForce_ = input.readFloat();
                break;
              }
              case 29: {
                bitField0_ |= 0x00000004;
                windAngle_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_SnowflakeTask_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_SnowflakeTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SnowflakeTask.class, Builder.class);
      }

      public static com.google.protobuf.Parser<SnowflakeTask> PARSER =
          new com.google.protobuf.AbstractParser<SnowflakeTask>() {
        public SnowflakeTask parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SnowflakeTask(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<SnowflakeTask> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int CURRENTSNOWFLAKESCOUNT_FIELD_NUMBER = 1;
      private int currentSnowflakesCount_;
      /**
       * <code>optional int32 currentSnowflakesCount = 1;</code>
       */
      public boolean hasCurrentSnowflakesCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 currentSnowflakesCount = 1;</code>
       */
      public int getCurrentSnowflakesCount() {
        return currentSnowflakesCount_;
      }

      public static final int WINDFORCE_FIELD_NUMBER = 2;
      private float windForce_;
      /**
       * <code>optional float windForce = 2;</code>
       */
      public boolean hasWindForce() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float windForce = 2;</code>
       */
      public float getWindForce() {
        return windForce_;
      }

      public static final int WINDANGLE_FIELD_NUMBER = 3;
      private float windAngle_;
      /**
       * <code>optional float windAngle = 3;</code>
       */
      public boolean hasWindAngle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float windAngle = 3;</code>
       */
      public float getWindAngle() {
        return windAngle_;
      }

      private void initFields() {
        currentSnowflakesCount_ = 0;
        windForce_ = 0F;
        windAngle_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, currentSnowflakesCount_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, windForce_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeFloat(3, windAngle_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, currentSnowflakesCount_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, windForce_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, windAngle_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static SnowflakeTask parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SnowflakeTask parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SnowflakeTask parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SnowflakeTask parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SnowflakeTask parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static SnowflakeTask parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static SnowflakeTask parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static SnowflakeTask parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static SnowflakeTask parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static SnowflakeTask parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(SnowflakeTask prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code commons.SnowflakeData.SnowflakeTask}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:commons.SnowflakeData.SnowflakeTask)
          SnowflakeTaskOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SnowflakeMessages.internal_static_commons_SnowflakeData_SnowflakeTask_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SnowflakeMessages.internal_static_commons_SnowflakeData_SnowflakeTask_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  SnowflakeTask.class, Builder.class);
        }

        // Construct using snowflakes.cuda.kask.eti.pg.gda.pl.commons.SnowflakeMessages.SnowflakeData.SnowflakeTask.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          currentSnowflakesCount_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          windForce_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          windAngle_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SnowflakeMessages.internal_static_commons_SnowflakeData_SnowflakeTask_descriptor;
        }

        public SnowflakeTask getDefaultInstanceForType() {
          return SnowflakeTask.getDefaultInstance();
        }

        public SnowflakeTask build() {
          SnowflakeTask result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public SnowflakeTask buildPartial() {
          SnowflakeTask result = new SnowflakeTask(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.currentSnowflakesCount_ = currentSnowflakesCount_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.windForce_ = windForce_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.windAngle_ = windAngle_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof SnowflakeTask) {
            return mergeFrom((SnowflakeTask)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(SnowflakeTask other) {
          if (other == SnowflakeTask.getDefaultInstance()) return this;
          if (other.hasCurrentSnowflakesCount()) {
            setCurrentSnowflakesCount(other.getCurrentSnowflakesCount());
          }
          if (other.hasWindForce()) {
            setWindForce(other.getWindForce());
          }
          if (other.hasWindAngle()) {
            setWindAngle(other.getWindAngle());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          SnowflakeTask parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (SnowflakeTask) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int currentSnowflakesCount_ ;
        /**
         * <code>optional int32 currentSnowflakesCount = 1;</code>
         */
        public boolean hasCurrentSnowflakesCount() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 currentSnowflakesCount = 1;</code>
         */
        public int getCurrentSnowflakesCount() {
          return currentSnowflakesCount_;
        }
        /**
         * <code>optional int32 currentSnowflakesCount = 1;</code>
         */
        public Builder setCurrentSnowflakesCount(int value) {
          bitField0_ |= 0x00000001;
          currentSnowflakesCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 currentSnowflakesCount = 1;</code>
         */
        public Builder clearCurrentSnowflakesCount() {
          bitField0_ = (bitField0_ & ~0x00000001);
          currentSnowflakesCount_ = 0;
          onChanged();
          return this;
        }

        private float windForce_ ;
        /**
         * <code>optional float windForce = 2;</code>
         */
        public boolean hasWindForce() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional float windForce = 2;</code>
         */
        public float getWindForce() {
          return windForce_;
        }
        /**
         * <code>optional float windForce = 2;</code>
         */
        public Builder setWindForce(float value) {
          bitField0_ |= 0x00000002;
          windForce_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float windForce = 2;</code>
         */
        public Builder clearWindForce() {
          bitField0_ = (bitField0_ & ~0x00000002);
          windForce_ = 0F;
          onChanged();
          return this;
        }

        private float windAngle_ ;
        /**
         * <code>optional float windAngle = 3;</code>
         */
        public boolean hasWindAngle() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional float windAngle = 3;</code>
         */
        public float getWindAngle() {
          return windAngle_;
        }
        /**
         * <code>optional float windAngle = 3;</code>
         */
        public Builder setWindAngle(float value) {
          bitField0_ |= 0x00000004;
          windAngle_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float windAngle = 3;</code>
         */
        public Builder clearWindAngle() {
          bitField0_ = (bitField0_ & ~0x00000004);
          windAngle_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:commons.SnowflakeData.SnowflakeTask)
      }

      static {
        defaultInstance = new SnowflakeTask(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:commons.SnowflakeData.SnowflakeTask)
    }

    private int bitField0_;
    public static final int MAP_FIELD_FIELD_NUMBER = 1;
    private java.util.List<MyMapField> mapField_;
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    public java.util.List<MyMapField> getMapFieldList() {
      return mapField_;
    }
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    public java.util.List<? extends MyMapFieldOrBuilder>
        getMapFieldOrBuilderList() {
      return mapField_;
    }
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    public int getMapFieldCount() {
      return mapField_.size();
    }
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    public MyMapField getMapField(int index) {
      return mapField_.get(index);
    }
    /**
     * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
     */
    public MyMapFieldOrBuilder getMapFieldOrBuilder(
        int index) {
      return mapField_.get(index);
    }

    public static final int TOTALMESSAGESIZE_FIELD_NUMBER = 2;
    private int totalMessageSize_;
    /**
     * <code>optional int32 totalMessageSize = 2;</code>
     */
    public boolean hasTotalMessageSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 totalMessageSize = 2;</code>
     */
    public int getTotalMessageSize() {
      return totalMessageSize_;
    }

    public static final int SLAVECAPACITY_FIELD_NUMBER = 3;
    private int slaveCapacity_;
    /**
     * <code>optional int32 slaveCapacity = 3;</code>
     */
    public boolean hasSlaveCapacity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 slaveCapacity = 3;</code>
     */
    public int getSlaveCapacity() {
      return slaveCapacity_;
    }

    public static final int SLAVEID_FIELD_NUMBER = 4;
    private int slaveId_;
    /**
     * <code>optional int32 slaveId = 4;</code>
     */
    public boolean hasSlaveId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 slaveId = 4;</code>
     */
    public int getSlaveId() {
      return slaveId_;
    }

    public static final int ENDOFWORK_FIELD_NUMBER = 5;
    private boolean endOfWork_;
    /**
     * <code>optional bool endOfWork = 5;</code>
     */
    public boolean hasEndOfWork() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool endOfWork = 5;</code>
     */
    public boolean getEndOfWork() {
      return endOfWork_;
    }

    public static final int SNOWFLAKETASK_FIELD_NUMBER = 6;
    private SnowflakeTask snowflakeTask_;
    /**
     * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
     */
    public boolean hasSnowflakeTask() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
     */
    public SnowflakeTask getSnowflakeTask() {
      return snowflakeTask_;
    }
    /**
     * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
     */
    public SnowflakeTaskOrBuilder getSnowflakeTaskOrBuilder() {
      return snowflakeTask_;
    }

    private void initFields() {
      mapField_ = java.util.Collections.emptyList();
      totalMessageSize_ = 0;
      slaveCapacity_ = 0;
      slaveId_ = 0;
      endOfWork_ = false;
      snowflakeTask_ = SnowflakeTask.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < mapField_.size(); i++) {
        output.writeMessage(1, mapField_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, totalMessageSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, slaveCapacity_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, slaveId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(5, endOfWork_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(6, snowflakeTask_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < mapField_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mapField_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalMessageSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, slaveCapacity_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, slaveId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, endOfWork_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, snowflakeTask_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SnowflakeData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SnowflakeData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SnowflakeData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SnowflakeData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SnowflakeData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SnowflakeData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SnowflakeData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SnowflakeData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SnowflakeData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SnowflakeData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SnowflakeData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code commons.SnowflakeData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:commons.SnowflakeData)
        SnowflakeDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SnowflakeData.class, Builder.class);
      }

      // Construct using snowflakes.cuda.kask.eti.pg.gda.pl.commons.SnowflakeMessages.SnowflakeData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapFieldFieldBuilder();
          getSnowflakeTaskFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (mapFieldBuilder_ == null) {
          mapField_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mapFieldBuilder_.clear();
        }
        totalMessageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        slaveCapacity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        slaveId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        endOfWork_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (snowflakeTaskBuilder_ == null) {
          snowflakeTask_ = SnowflakeTask.getDefaultInstance();
        } else {
          snowflakeTaskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SnowflakeMessages.internal_static_commons_SnowflakeData_descriptor;
      }

      public SnowflakeData getDefaultInstanceForType() {
        return SnowflakeData.getDefaultInstance();
      }

      public SnowflakeData build() {
        SnowflakeData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SnowflakeData buildPartial() {
        SnowflakeData result = new SnowflakeData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (mapFieldBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            mapField_ = java.util.Collections.unmodifiableList(mapField_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mapField_ = mapField_;
        } else {
          result.mapField_ = mapFieldBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.totalMessageSize_ = totalMessageSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.slaveCapacity_ = slaveCapacity_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.slaveId_ = slaveId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.endOfWork_ = endOfWork_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        if (snowflakeTaskBuilder_ == null) {
          result.snowflakeTask_ = snowflakeTask_;
        } else {
          result.snowflakeTask_ = snowflakeTaskBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SnowflakeData) {
          return mergeFrom((SnowflakeData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SnowflakeData other) {
        if (other == SnowflakeData.getDefaultInstance()) return this;
        if (mapFieldBuilder_ == null) {
          if (!other.mapField_.isEmpty()) {
            if (mapField_.isEmpty()) {
              mapField_ = other.mapField_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMapFieldIsMutable();
              mapField_.addAll(other.mapField_);
            }
            onChanged();
          }
        } else {
          if (!other.mapField_.isEmpty()) {
            if (mapFieldBuilder_.isEmpty()) {
              mapFieldBuilder_.dispose();
              mapFieldBuilder_ = null;
              mapField_ = other.mapField_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mapFieldBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMapFieldFieldBuilder() : null;
            } else {
              mapFieldBuilder_.addAllMessages(other.mapField_);
            }
          }
        }
        if (other.hasTotalMessageSize()) {
          setTotalMessageSize(other.getTotalMessageSize());
        }
        if (other.hasSlaveCapacity()) {
          setSlaveCapacity(other.getSlaveCapacity());
        }
        if (other.hasSlaveId()) {
          setSlaveId(other.getSlaveId());
        }
        if (other.hasEndOfWork()) {
          setEndOfWork(other.getEndOfWork());
        }
        if (other.hasSnowflakeTask()) {
          mergeSnowflakeTask(other.getSnowflakeTask());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SnowflakeData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SnowflakeData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<MyMapField> mapField_ =
        java.util.Collections.emptyList();
      private void ensureMapFieldIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          mapField_ = new java.util.ArrayList<MyMapField>(mapField_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          MyMapField, MyMapField.Builder, MyMapFieldOrBuilder> mapFieldBuilder_;

      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public java.util.List<MyMapField> getMapFieldList() {
        if (mapFieldBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mapField_);
        } else {
          return mapFieldBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public int getMapFieldCount() {
        if (mapFieldBuilder_ == null) {
          return mapField_.size();
        } else {
          return mapFieldBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public MyMapField getMapField(int index) {
        if (mapFieldBuilder_ == null) {
          return mapField_.get(index);
        } else {
          return mapFieldBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder setMapField(
          int index, MyMapField value) {
        if (mapFieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapFieldIsMutable();
          mapField_.set(index, value);
          onChanged();
        } else {
          mapFieldBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder setMapField(
          int index, MyMapField.Builder builderForValue) {
        if (mapFieldBuilder_ == null) {
          ensureMapFieldIsMutable();
          mapField_.set(index, builderForValue.build());
          onChanged();
        } else {
          mapFieldBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder addMapField(MyMapField value) {
        if (mapFieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapFieldIsMutable();
          mapField_.add(value);
          onChanged();
        } else {
          mapFieldBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder addMapField(
          int index, MyMapField value) {
        if (mapFieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapFieldIsMutable();
          mapField_.add(index, value);
          onChanged();
        } else {
          mapFieldBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder addMapField(
          MyMapField.Builder builderForValue) {
        if (mapFieldBuilder_ == null) {
          ensureMapFieldIsMutable();
          mapField_.add(builderForValue.build());
          onChanged();
        } else {
          mapFieldBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder addMapField(
          int index, MyMapField.Builder builderForValue) {
        if (mapFieldBuilder_ == null) {
          ensureMapFieldIsMutable();
          mapField_.add(index, builderForValue.build());
          onChanged();
        } else {
          mapFieldBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder addAllMapField(
          Iterable<? extends MyMapField> values) {
        if (mapFieldBuilder_ == null) {
          ensureMapFieldIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mapField_);
          onChanged();
        } else {
          mapFieldBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder clearMapField() {
        if (mapFieldBuilder_ == null) {
          mapField_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mapFieldBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public Builder removeMapField(int index) {
        if (mapFieldBuilder_ == null) {
          ensureMapFieldIsMutable();
          mapField_.remove(index);
          onChanged();
        } else {
          mapFieldBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public MyMapField.Builder getMapFieldBuilder(
          int index) {
        return getMapFieldFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public MyMapFieldOrBuilder getMapFieldOrBuilder(
          int index) {
        if (mapFieldBuilder_ == null) {
          return mapField_.get(index);  } else {
          return mapFieldBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public java.util.List<? extends MyMapFieldOrBuilder>
           getMapFieldOrBuilderList() {
        if (mapFieldBuilder_ != null) {
          return mapFieldBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mapField_);
        }
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public MyMapField.Builder addMapFieldBuilder() {
        return getMapFieldFieldBuilder().addBuilder(
            MyMapField.getDefaultInstance());
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public MyMapField.Builder addMapFieldBuilder(
          int index) {
        return getMapFieldFieldBuilder().addBuilder(
            index, MyMapField.getDefaultInstance());
      }
      /**
       * <code>repeated .commons.SnowflakeData.MyMapField map_field = 1;</code>
       */
      public java.util.List<MyMapField.Builder>
           getMapFieldBuilderList() {
        return getMapFieldFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          MyMapField, MyMapField.Builder, MyMapFieldOrBuilder>
          getMapFieldFieldBuilder() {
        if (mapFieldBuilder_ == null) {
          mapFieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              MyMapField, MyMapField.Builder, MyMapFieldOrBuilder>(
                  mapField_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          mapField_ = null;
        }
        return mapFieldBuilder_;
      }

      private int totalMessageSize_ ;
      /**
       * <code>optional int32 totalMessageSize = 2;</code>
       */
      public boolean hasTotalMessageSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 totalMessageSize = 2;</code>
       */
      public int getTotalMessageSize() {
        return totalMessageSize_;
      }
      /**
       * <code>optional int32 totalMessageSize = 2;</code>
       */
      public Builder setTotalMessageSize(int value) {
        bitField0_ |= 0x00000002;
        totalMessageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalMessageSize = 2;</code>
       */
      public Builder clearTotalMessageSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalMessageSize_ = 0;
        onChanged();
        return this;
      }

      private int slaveCapacity_ ;
      /**
       * <code>optional int32 slaveCapacity = 3;</code>
       */
      public boolean hasSlaveCapacity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 slaveCapacity = 3;</code>
       */
      public int getSlaveCapacity() {
        return slaveCapacity_;
      }
      /**
       * <code>optional int32 slaveCapacity = 3;</code>
       */
      public Builder setSlaveCapacity(int value) {
        bitField0_ |= 0x00000004;
        slaveCapacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 slaveCapacity = 3;</code>
       */
      public Builder clearSlaveCapacity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        slaveCapacity_ = 0;
        onChanged();
        return this;
      }

      private int slaveId_ ;
      /**
       * <code>optional int32 slaveId = 4;</code>
       */
      public boolean hasSlaveId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 slaveId = 4;</code>
       */
      public int getSlaveId() {
        return slaveId_;
      }
      /**
       * <code>optional int32 slaveId = 4;</code>
       */
      public Builder setSlaveId(int value) {
        bitField0_ |= 0x00000008;
        slaveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 slaveId = 4;</code>
       */
      public Builder clearSlaveId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        slaveId_ = 0;
        onChanged();
        return this;
      }

      private boolean endOfWork_ ;
      /**
       * <code>optional bool endOfWork = 5;</code>
       */
      public boolean hasEndOfWork() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool endOfWork = 5;</code>
       */
      public boolean getEndOfWork() {
        return endOfWork_;
      }
      /**
       * <code>optional bool endOfWork = 5;</code>
       */
      public Builder setEndOfWork(boolean value) {
        bitField0_ |= 0x00000010;
        endOfWork_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool endOfWork = 5;</code>
       */
      public Builder clearEndOfWork() {
        bitField0_ = (bitField0_ & ~0x00000010);
        endOfWork_ = false;
        onChanged();
        return this;
      }

      private SnowflakeTask snowflakeTask_ = SnowflakeTask.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SnowflakeTask, SnowflakeTask.Builder, SnowflakeTaskOrBuilder> snowflakeTaskBuilder_;
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public boolean hasSnowflakeTask() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public SnowflakeTask getSnowflakeTask() {
        if (snowflakeTaskBuilder_ == null) {
          return snowflakeTask_;
        } else {
          return snowflakeTaskBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public Builder setSnowflakeTask(SnowflakeTask value) {
        if (snowflakeTaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          snowflakeTask_ = value;
          onChanged();
        } else {
          snowflakeTaskBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public Builder setSnowflakeTask(
          SnowflakeTask.Builder builderForValue) {
        if (snowflakeTaskBuilder_ == null) {
          snowflakeTask_ = builderForValue.build();
          onChanged();
        } else {
          snowflakeTaskBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public Builder mergeSnowflakeTask(SnowflakeTask value) {
        if (snowflakeTaskBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              snowflakeTask_ != SnowflakeTask.getDefaultInstance()) {
            snowflakeTask_ =
              SnowflakeTask.newBuilder(snowflakeTask_).mergeFrom(value).buildPartial();
          } else {
            snowflakeTask_ = value;
          }
          onChanged();
        } else {
          snowflakeTaskBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public Builder clearSnowflakeTask() {
        if (snowflakeTaskBuilder_ == null) {
          snowflakeTask_ = SnowflakeTask.getDefaultInstance();
          onChanged();
        } else {
          snowflakeTaskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public SnowflakeTask.Builder getSnowflakeTaskBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getSnowflakeTaskFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      public SnowflakeTaskOrBuilder getSnowflakeTaskOrBuilder() {
        if (snowflakeTaskBuilder_ != null) {
          return snowflakeTaskBuilder_.getMessageOrBuilder();
        } else {
          return snowflakeTask_;
        }
      }
      /**
       * <code>optional .commons.SnowflakeData.SnowflakeTask snowflakeTask = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SnowflakeTask, SnowflakeTask.Builder, SnowflakeTaskOrBuilder>
          getSnowflakeTaskFieldBuilder() {
        if (snowflakeTaskBuilder_ == null) {
          snowflakeTaskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SnowflakeTask, SnowflakeTask.Builder, SnowflakeTaskOrBuilder>(
                  getSnowflakeTask(),
                  getParentForChildren(),
                  isClean());
          snowflakeTask_ = null;
        }
        return snowflakeTaskBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:commons.SnowflakeData)
    }

    static {
      defaultInstance = new SnowflakeData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:commons.SnowflakeData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commons_SnowflakeData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_commons_SnowflakeData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commons_SnowflakeData_MyMapField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_commons_SnowflakeData_MyMapField_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commons_SnowflakeData_SnowflakeTask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_commons_SnowflakeData_SnowflakeTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027snowflakeMessages.proto\022\007commons\"\330\002\n\rS" +
      "nowflakeData\0224\n\tmap_field\030\001 \003(\0132!.common" +
      "s.SnowflakeData.MyMapField\022\030\n\020totalMessa" +
      "geSize\030\002 \001(\005\022\025\n\rslaveCapacity\030\003 \001(\005\022\017\n\007s" +
      "laveId\030\004 \001(\005\022\021\n\tendOfWork\030\005 \001(\010\022;\n\rsnowf" +
      "lakeTask\030\006 \001(\0132$.commons.SnowflakeData.S" +
      "nowflakeTask\032(\n\nMyMapField\022\013\n\003key\030\001 \001(\005\022" +
      "\r\n\005value\030\002 \003(\002\032U\n\rSnowflakeTask\022\036\n\026curre" +
      "ntSnowflakesCount\030\001 \001(\005\022\021\n\twindForce\030\002 \001" +
      "(\002\022\021\n\twindAngle\030\003 \001(\002B?\n*snowflakes.cuda",
      ".kask.eti.pg.gda.pl.commonsB\021SnowflakeMe" +
      "ssages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_commons_SnowflakeData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_commons_SnowflakeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_commons_SnowflakeData_descriptor,
        new String[] { "MapField", "TotalMessageSize", "SlaveCapacity", "SlaveId", "EndOfWork", "SnowflakeTask", });
    internal_static_commons_SnowflakeData_MyMapField_descriptor =
      internal_static_commons_SnowflakeData_descriptor.getNestedTypes().get(0);
    internal_static_commons_SnowflakeData_MyMapField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_commons_SnowflakeData_MyMapField_descriptor,
        new String[] { "Key", "Value", });
    internal_static_commons_SnowflakeData_SnowflakeTask_descriptor =
      internal_static_commons_SnowflakeData_descriptor.getNestedTypes().get(1);
    internal_static_commons_SnowflakeData_SnowflakeTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_commons_SnowflakeData_SnowflakeTask_descriptor,
        new String[] { "CurrentSnowflakesCount", "WindForce", "WindAngle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
